import "./App.css";
import login from "./Login/login";
import Navbar_com from "./navbar";

function App() {
  return (
    <div className="app">
      <Navbar_com />
      <div className="app-event">
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
        <div> pic1 </div>
        <div> pic2 </div>
        <div> pic3 </div>
        <div> pic4 </div>
        <div> pic5 </div>
        <div> pic6 </div>
        <div> pic7 </div>
        <div> pic8 </div>
        <div> pic9 </div>
        <div> pic10 </div>
        <div> pic11 </div>
        <div> pic12 </div>
      </div>
    </div>
  );
}

export default App;
